version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: choco upgrade chocolatey
before_build:
- cmd: nuget restore
build:
  verbosity: normal
artifacts:
- path: Installer\bin\Release\QueryMultiDb.msi
  name: Installer
- path: Installer\bin\Release\QueryMultiDb.*.nupkg
  name: Chocolatey package
