version: 1.0.{build}
image: Visual Studio 2019
configuration: Release

environment:
  Appveyor: true
  COVERALLS_REPO_TOKEN:
    secure: D2UAgklYO9LG75FbrhhO43JKZSQ16xnxlyY/Y9SmR+1m8zAhuEcM02gN7GhPBevj
  CODECOV_TOKEN:
    secure: 231c53a0-46d7-429e-9de6-0a86d1ecb98a

services:
  - mssql2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
- cmd: >-
    choco upgrade chocolatey

    choco install codecov

    choco install opencover.portable

# dotnet tool install -g coveralls.net
before_build:
- cmd: >-
    nuget restore

build:
  verbosity: normal

test_script:
- cmd: >-
    OpenCover.Console.exe -register -target:"%xunit20%\xunit.console.exe" -targetargs:"\"C:\projects\querymultidb\QueryMultiDb.Tests.Unit\bin\Release\QueryMultiDb.Tests.Unit.dll\" \"C:\projects\querymultidb\QueryMultiDb.Common.Tests.Unit\bin\Release\QueryMultiDb.Common.Tests.Unit.dll\" \"C:\projects\querymultidb\QueryMultiDb.Tests.System\bin\Release\QueryMultiDb.Tests.System.dll\" -noshadow -appveyor -xml C:\projects\querymultidb\QueryMultiDb.Tests.Unit.report.xml" -output:"QueryMultiDb.Tests.Unit.coverage.xml" -filter:"+[QueryMultiDb*]*"

    codecov -f "QueryMultiDb.Tests.Unit.coverage.xml" -t 231c53a0-46d7-429e-9de6-0a86d1ecb98a

# csmacnz.coveralls.exe --opencover -i "QueryMultiDb.Tests.Unit.coverage.xml" --repoToken %COVERALLS_REPO_TOKEN%

artifacts:
- path: Installer\bin\Release\QueryMultiDb.msi
  name: Installer
- path: Installer\bin\Release\QueryMultiDb.*.nupkg
  name: Chocolatey package
